package wordProcessor;
import Sandhis.*;
import Matra.*;
import java.io.*;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
import transliteration.*;

/**
 *
 * @author priya
 */
public class Wordprocessor extends javax.swing.JFrame {

    public Wordprocessor(java.awt.Frame parent, boolean modal) {
       // super(parent, modal);
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextPane1.setFont(new java.awt.Font("xdvng", 0, 18)); // NOI18N
        jTextPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextPane1MouseReleased(evt);
            }
        });
        jTextPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTextPane1MouseDragged(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 600, 350);

        jLabel1.setBackground(java.awt.Color.red);
        jLabel1.setForeground(java.awt.Color.red);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1349, 83, 0, 0);

        jLabel2.setBackground(new java.awt.Color(226, 227, 240));
        jLabel2.setForeground(java.awt.Color.blue);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1349, 94, 0, 0);

        jLabel3.setBackground(java.awt.Color.yellow);
        jLabel3.setForeground(java.awt.Color.green);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1349, 257, 0, 0);

        jTextPane2.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        jTextPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextPane2MouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(620, 30, 560, 240);

        jTextPane3.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        jScrollPane3.setViewportView(jTextPane3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(620, 290, 560, 190);

        jTextPane4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextPane4KeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTextPane4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(10, 380, 600, 310);

        jLabel4.setText("Enter Your Text in Itrans Form...");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 360, 210, 14);

        jLabel5.setText("Output of Sandhi Join");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(620, 270, 200, 14);

        jLabel6.setText("Output of Sandhi Viched");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(620, 10, 220, 14);

        jScrollPane5.setViewportView(jTextPane5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(620, 500, 560, 190);

        jLabel7.setText("Output of Vrutta ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(620, 480, 140, 14);

        jMenu1.setText("File");

        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Add To Dictionary");
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu3MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sandhi Viched");
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Sandhi Join");
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu5MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Vrutta");
        jMenu6.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu6MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Wordprocessor(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }
    connect c = new connect();
    Connection con = (Connection) c.connection();    String str, str1;

    void printMeaning(String word) {
        db dbObject=new db();
        String result="",resultMeaning="";
        String[] arr=new String[2];
        arr=word.split(" ");
        String meaning;
        for(int i=0;i<arr.length;i++)
        {
            meaning = " ";
            meaning=dbObject.findMeaning(arr[i]);
            if(meaning==null)
            {
                meaning="Meaning Not found";
            }
            result=result+" " +arr[i]; resultMeaning=resultMeaning+" "+meaning;
            
        }
        jTextPane2.setText(jTextPane2.getText()+result+resultMeaning+"\n");
            result="";resultMeaning="";
        jTextPane2.setText(jTextPane2.getText()+"\n");

    }
    String getMeaning (String word)
    {
        db dbObject=new db();
        String meaning;
        meaning=dbObject.findMeaning(word);
        return meaning;
    }
    void sandhiViched(String word) {
        try {
            
            ResultSet S = null;
            PreparedStatement stat = (PreparedStatement) con.prepareStatement("SELECT meaning FROM Dict where word = CONVERT('" + word + "' USING utf8)");
            S = stat.executeQuery();
            if (S.next()) {
                System.out.print("present");
                JOptionPane.showMessageDialog(null, S.getString(1));
                
            } else {
//                PatternMatch pm = new PatternMatch();
//                ArrayList<String> arr1 = new ArrayList<String>();
//                arr1 = pm.sandhiPatternCheck(word);
//                if (arr1.isEmpty()) {
                
                    mulitipleSplit ms = new mulitipleSplit();
                    ArrayList<String> solution = ms.process(word);
                    String Result="";
                    System.out.println("Result");
                    for (int i = 0; i < solution.size(); i++) {
                        if(i==solution.size()-1)
                            Result=Result+solution.get(i)+"("+getMeaning(solution.get(i))+")";
                        else
                            Result=Result+solution.get(i)+"("+getMeaning(solution.get(i))+")+";
                    }
                    if(!Result.equals(""))
                        jTextPane2.setText(Result+" = "+word);
//                }
            }
    }
    
    catch (Exception e) {
                e.printStackTrace();
    }
}
    private void jTextPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPane1MouseReleased
try {
        str=jTextPane1.getSelectedText();
         System.out.println(str);
         if (str != null)
          sandhiViched(str.trim());
       }
       catch (Exception e) {
        e.printStackTrace();
      }
      
    }//GEN-LAST:event_jTextPane1MouseReleased

    private void jTextPane1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPane1MouseDragged
        str1 = "";
        str = jTextPane1.getSelectedText();
        jTextPane2.setText("");
        str1 = str;
    }//GEN-LAST:event_jTextPane1MouseDragged

    private void jTextPane2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPane2MouseReleased
     
    }//GEN-LAST:event_jTextPane2MouseReleased

    public String getLastWord(String word)
    {
    	String lastWord;
    	String array[] = word.split(" ");
    	lastWord=array[array.length-1];
    	return lastWord;
    }
    
    choose_encoding encod=new choose_encoding();
    
    private void jTextPane4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPane4KeyReleased
         String str1 = "";//(tf1.getText().toString()).trim();

	if(evt.getComponent() == this.jTextPane4 )
        {
		str1 = jTextPane4.getText();
		jTextPane1.setText(encod.get_raw_to_dvn_view(str1));
         }
    }//GEN-LAST:event_jTextPane4KeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try
        {
                File file=null;
                JFileChooser chooser = new JFileChooser();
                int returnVal = chooser.showOpenDialog(null);
                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    file = chooser.getSelectedFile();
                    
                    }
                String path = file.getPath();
                FileInputStream fis=new FileInputStream(path);
                BufferedReader myReader = new BufferedReader(
					new InputStreamReader(fis));
                String aDataRow = "";
		String aBuffer = "";
		while ((aDataRow = myReader.readLine()) != null) {
				aBuffer += aDataRow + "\n";
			}
                String str = aBuffer.toString();
                System.out.println(str);
                jTextPane1.setText(str);
                
                fis.close();
            }
        catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try
        {
            String s=jTextPane1.getText();
            if(s.length()>0)
            {
                File file=null;
                JFileChooser chooser = new JFileChooser();
                int returnVal = chooser.showSaveDialog(null);
                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    file = chooser.getSelectedFile();
                    
                    }
                String path = file.getPath();    
                FileOutputStream fos=new FileOutputStream(path);
                System.out.println(s);
                byte[] b=s.getBytes();
                fos.write(b);
                fos.close();
            }
        }catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu3MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuSelected
            saveMeaning MyDialog = new saveMeaning(this,true);
            MyDialog.jTextField1.setText(jTextPane1.getSelectedText());
            MyDialog.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MenuSelected

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
            String TextArea=jTextPane1.getSelectedText();//jTextPane1.getText();
        String[] arrayOfWords=TextArea.split(" ");
        for(int i=0;i<arrayOfWords.length;i++)
            //jTextPane2.setText(jTextPane2.getText()+" "+arrayOfWords[i]);
        sandhiViched(arrayOfWords[i]);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MenuSelected

    private void jMenu5MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu5MenuSelected
               String word=null;
        word=jTextPane2.getSelectedText();
        String[] arr;
        if( word!=null)
        {
         arr=word.split(" ");
        }
        else 
        {
            arr=jTextPane1.getSelectedText().split(" ");
        }
        if(arr.length>1)
        {
        join j=new join();
        String[] finalResult= new String[arr.length];
        System.out.println(arr.length);
        String result=j.performJoin(arr[0],arr[1]);
        int x=0;
        if(result.indexOf(" ")!=-1)
        {
        	String[] temp=result.split(" ");
        	finalResult[0]=temp[0];
        	finalResult[1]=temp[1];
        	x++;
        }
        else
        {
        	finalResult[0]=result;
        	
        }
        for(int i=2;i<arr.length;i++)
        {
            if(arr[i].trim()!="")
            { 
            	System.out.println(x+" "+i);
            	System.out.println(" "+finalResult[x]);
                result=j.performJoin(finalResult[x],arr[i]); 
                if(result.indexOf(" ")!=-1)
                {
                	x++;
                	finalResult[x]=getLastWord(result);
                }
                else
                {
                	finalResult[x]=result;
                }
            }
        }
       
        for(int i=0;i<=x;i++)
        {
        	System.out.println(finalResult[i]);
            jTextPane3.setText(jTextPane3.getText()+" "+finalResult[i]);
        }
        }

    }//GEN-LAST:event_jMenu5MenuSelected

    private void jMenu6MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu6MenuSelected
                
        String string1;
        if(!jTextPane1.getSelectedText().trim().equals(""))
        {
            string1=jTextPane1.getSelectedText().trim();
        }
        else 
            string1=jTextPane2.getSelectedText().trim();
        string1=string1.trim();
        Matra m=new Matra();
        join j=new join();
        string1=j.StoE(string1);
        jTextPane5.setText(m.vrutta(string1));

    }//GEN-LAST:event_jMenu6MenuSelected
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Wordprocessor dialog = new Wordprocessor(new javax.swing.JFrame(), true);
                dialog.setSize(1200,730);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    // End of variables declaration//GEN-END:variables
}
